### PR TITLE
feat/EC-31 define category

### PR DESCRIPTION
**Pull request by JohannaStoicanescu**
- add entitie category
- create, delete methods
- resolver graphql  
- spaces in user.ts file

Don't bother looking at user.ts file, it's just Prettier's modifications

### CODE REVIEW

**Review by JonasJallet — CHANGES_REQUESTED** [review]
Maybe you can add relation for category with place in your PR

**Review by JohannaStoicanescu — COMMENTED** [review]
Is it the purpose of this pr ?

**Review by JonasJallet — APPROVED** [review]

**Review by PaulineHavez — APPROVED** [review]

**Review by VinchC — APPROVED** [review]
Top bravo!

**Pull request merged**
